In [24]:
from scipy import stats as sts
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv("socialmobility.csv")
data

          father           son  count
0           farm          farm    703
1           farm     unskilled   1478
2           farm       skilled   1430
3           farm  professional   1109
4      unskilled          farm     58
5      unskilled     unskilled   1756
6      unskilled       skilled   1630
7      unskilled  professional   1568
8        skilled          farm     63
9        skilled     unskilled   1453
10       skilled       skilled   2068
11       skilled  professional   2483
12  professional          farm     61
13  professional     unskilled    749
14  professional       skilled   1183
15  professional  professional   3315

In [48]:
subset = data[data.father == "unskilled"]
"""
Setting a uniform distribution over 
the probability vector parameter of the multinomial.
"""
alpha_priors = np.repeat(1, len(subset))
"""
based on the conjugate prior table, we can compute the posterior 
hyperparameters of the Dirichlet posterior distribution by
"""
alpha_posteriors = [alpha_priors[i] + subset['count'].iloc[i] for i in range(len(subset))]

posterior = sts.dirichlet(alpha_posteriors)

samples = posterior.rvs(size=10**5)

"""
What is the posterior 95% probability interval over the probability that a son will
become a skilled laborer if his father was an unskilled laborer?
"""
print("95% CI that the son is skilled while father is unskilled\n",
      np.percentile(samples[:,2], [2.5, 97.5]))


"""
What is the posterior 95% probability interval over the probability that a son will
become a professional laborer if his father was an unskilled laborer?
"""
print("\n95% CI that the son is professional while father is unskilled\n",
      np.percentile(samples[:,3], [2.5, 97.5]))

95% CI that the son is skilled while father is unskilled
 [0.31220254 0.33826378]

95% CI that the son is professional while father is unskilled
 [0.30010122 0.32565323]

In [53]:
"""
What is the posterior 95% probability interval over the probability that a father 
works on a farm if his son works as a professional?
"""

subset2 = data[data.son == "professional"]
print(subset2)
alpha_priors = np.repeat(1, len(subset2))

alpha_posteriors = [alpha_priors[i] + subset2['count'].iloc[i] for i in range(len(subset2))]

posterior2 = sts.dirichlet(alpha_posteriors)
samples2 = posterior2.rvs(size=10**5)

print("\n95% CI that father works in a farm if son is a professional\n",
      np.percentile(samples2[:,0], [2.5, 97.5]))

          father           son  count
3           farm  professional   1109
7      unskilled  professional   1568
11       skilled  professional   2483
15  professional  professional   3315

95% CI that father works in a farm if son is a professional
 [0.12379266 0.13817723]